# -*- coding: utf-8 -*-
"""CKD_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xaIaaKG-MZfue4KLbGXa1Vd4GmPtBo5s
"""

# Age, Blood Pressure, Blood Sugar, Serum Creatinine,
# Hemoglobin, eGFR, Albumin, CKD

patients = [
    [25,120,90,0.8,14.5,110,0,0],
    [34,130,110,1.0,13.8,98,1,0],
    [45,145,190,2.2,10.5,55,3,1],
    [50,160,240,3.1,9.5,35,4,1],
    [67,170,260,3.8,8.8,25,5,1],
    [29,118,100,0.9,15.0,115,0,0],
    [39,125,105,1.1,13.9,100,1,0],
    [55,150,210,2.6,10.2,48,3,1],
    [61,155,220,2.9,9.8,42,4,1],
    [48,138,170,1.4,12.5,72,2,0],
    [70,180,300,4.5,8.0,18,5,1],
    [42,132,115,1.0,13.2,96,1,0],
    [58,148,195,2.4,10.8,52,3,1],
    [36,126,108,0.9,14.2,102,0,0],
    [64,162,235,3.3,9.1,30,4,1],
    [47,140,180,1.6,11.8,65,2,0],
    [31,122,95,0.8,14.8,108,0,0],
    [53,152,205,2.8,10.0,45,3,1],
    [68,175,275,4.0,8.5,20,5,1],
    [40,128,112,1.1,13.5,97,1,0],
    [60,158,225,3.0,9.6,40,4,1],
    [37,124,104,0.9,14.1,101,0,0],
    [57,149,200,2.5,10.4,50,3,1],
    [44,136,165,1.3,12.9,75,2,0],
    [66,168,255,3.7,8.9,28,5,1],
    [30,121,98,0.8,14.7,109,0,0],
    [51,147,192,2.3,10.7,54,3,1],
    [63,165,245,3.5,9.2,32,4,1],
    [35,127,109,1.0,14.0,103,1,0],
    [56,151,215,2.7,10.1,47,3,1],
    [69,178,285,4.2,8.3,22,5,1],
    [43,133,118,1.1,13.3,95,1,0],
    [59,154,218,2.9,9.9,43,4,1],
    [46,137,172,1.5,12.3,70,2,0],
    [65,166,250,3.6,9.0,29,5,1],
    [32,123,97,0.9,14.6,107,0,0],
    [54,153,208,2.8,10.3,46,3,1],
    [71,182,310,4.7,7.9,16,5,1],
    [41,129,114,1.1,13.4,99,1,0],
    [52,146,198,2.4,10.6,53,3,1],
    [38,126,106,0.9,14.3,104,0,0],
    [62,160,230,3.2,9.4,38,4,1],
    [49,139,175,1.5,12.1,68,2,0],
    [72,185,320,5.0,7.5,15,5,1],
    [33,124,102,0.9,14.4,106,0,0],
    [58,150,212,2.6,10.2,49,3,1],
    [45,135,160,1.2,12.8,78,2,0],
    [67,172,265,3.9,8.7,24,5,1],
    [28,119,92,0.8,14.9,112,0,0],
    [55,148,205,2.5,10.5,51,3,1]
]

print("Dataset Loaded Successfully")
print("Total Records:", len(patients))

"""1. Patient Statistics
Write a program to calculate and display:

•	Total number of patients.

•	Total number of CKD patients.

•	Total number of Non-CKD patients.

•	Percentage of CKD patients rounded to two decimal places.

"""

# Question 1 : Patient Statistics

total_patients = len(patients)

ckd = 0
non_ckd = 0

for patient in patients:
    if patient[7] == 1:
        ckd += 1
    else:
        non_ckd += 1

percentage = (ckd / total_patients) * 100

print("Total Patients :", total_patients)
print("CKD Patients :", ckd)
print("Non CKD Patients :", non_ckd)
print("CKD Percentage :", round(percentage,2),"%")

"""2. Age Analysis

Write a program to find:

•	Youngest patient's age.

•	Oldest patient's age.

•	Average age of all patients rounded to two decimal places.

"""

# Question 2 : Age Analysis

ages = []

for patient in patients:
    ages.append(patient[0])

print("Youngest Age :", min(ages))
print("Oldest Age :", max(ages))
print("Average Age :", round(sum(ages)/len(ages),2))

"""3. Blood Pressure Risk Analysis

Display every patient whose Blood Pressure is greater than 140 mmHg.
Also display the total number of such patients.

"""

count = 0

print("Patients with Blood Pressure > 140\n")

for patient in patients:

    if patient[1] > 140:
        print(patient)
        count += 1

print("Total Patients :", count)

"""4. Blood Sugar Analysis

Display every patient whose Blood Sugar is greater than 180 mg/dL.
Calculate and display the average Blood Sugar of only these patients.

"""

count = 0
total = 0

print("Patients with Blood Sugar > 180\n")

for patient in patients:

    if patient[2] > 180:

        print(patient)

        total += patient[2]

        count += 1

print("Average Blood Sugar :", round(total/count,2))

"""5. Kidney Function Assessment

Display all patients whose eGFR is less than 60.
Also display how many patients satisfy this condition.

"""

count = 0

print("Patients with eGFR < 60\n")

for patient in patients:

    if patient[5] < 60:

        print(patient)

        count += 1

print("Total Patients :", count)

"""6. Serum Creatinine Report

Calculate and display:

•	Average Serum Creatinine.

•	Highest Serum Creatinine.

•	Lowest Serum Creatinine.

•	Number of patients whose Serum Creatinine is greater than 2.0 mg/dL.


"""

creatinine = []

high_creatinine = 0

for patient in patients:
    creatinine.append(patient[3])

    if patient[3] > 2.0:
        high_creatinine += 1

print("Average Serum Creatinine :", round(sum(creatinine)/len(creatinine),2))
print("Highest Serum Creatinine :", max(creatinine))
print("Lowest Serum Creatinine :", min(creatinine))
print("Patients with Serum Creatinine > 2.0 :", high_creatinine)

"""7. Hemoglobin Comparison

Separate CKD and Non-CKD patients.

Calculate the average Hemoglobin for each group and clearly mention which group has the lower average Hemoglobin.

"""

ckd_hb = []
non_ckd_hb = []

for patient in patients:

    if patient[7] == 1:
        ckd_hb.append(patient[4])
    else:
        non_ckd_hb.append(patient[4])

avg_ckd = sum(ckd_hb)/len(ckd_hb)
avg_non = sum(non_ckd_hb)/len(non_ckd_hb)

print("Average Hemoglobin (CKD) :", round(avg_ckd,2))
print("Average Hemoglobin (Non CKD) :", round(avg_non,2))

if avg_ckd < avg_non:
    print("CKD patients have lower average Hemoglobin.")
else:
    print("Non CKD patients have lower average Hemoglobin.")

"""8. Albumin Distribution

Count the number of patients having Albumin values 0, 1, 2, 3, 4 and 5 separately.

Finally display the Albumin level that occurs most frequently.

"""

albumin_count = [0,0,0,0,0,0]

for patient in patients:

    albumin = patient[6]

    albumin_count[albumin] += 1

print("Albumin 0 :", albumin_count[0])
print("Albumin 1 :", albumin_count[1])
print("Albumin 2 :", albumin_count[2])
print("Albumin 3 :", albumin_count[3])
print("Albumin 4 :", albumin_count[4])
print("Albumin 5 :", albumin_count[5])

highest = max(albumin_count)

for i in range(len(albumin_count)):
    if albumin_count[i] == highest:
        print("Most Frequent Albumin Level :", i)

"""9. High-Risk Patient Identification

Display every patient satisfying ALL of the following conditions:

•	Blood Pressure > 150

•	Blood Sugar > 180

•	Serum Creatinine > 2.5

•	eGFR < 45

Also display the total number of high-risk patients.

"""

count = 0

print("High Risk Patients")

for patient in patients:

    if patient[1] > 150 and patient[2] > 180 and patient[3] > 2.5 and patient[5] < 45:

        print(patient)

        count += 1

print("Total High Risk Patients :", count)

"""10. Kidney Health Risk Score

Assign one risk point for each condition:

•	Blood Pressure > 140

•	Blood Sugar > 180

•	Serum Creatinine > 2.0

•	eGFR < 60

•	Albumin ≥ 3

Calculate every patient's total risk score (0–5) and display the patient(s) having the highest risk score.

"""

highest_score = 0

risk_scores = []

for patient in patients:

    score = 0

    if patient[1] > 140:
        score += 1

    if patient[2] > 180:
        score += 1

    if patient[3] > 2.0:
        score += 1

    if patient[5] < 60:
        score += 1

    if patient[6] >= 3:
        score += 1

    risk_scores.append(score)

    if score > highest_score:
        highest_score = score

print("Highest Risk Score :", highest_score)

print("Patients with Highest Risk Score")

for i in range(len(patients)):

    if risk_scores[i] == highest_score:

        print(patients[i], "Risk Score =", risk_scores[i])

"""11. Best and Worst Kidney Function

Sort the dataset using eGFR.

Display:

•	Top 5 healthiest patients (highest eGFR).

•	Top 5 most critical patients (lowest eGFR).

"""

sorted_patients = sorted(patients, key=lambda x: x[5])

print("\nTop 5 Most Critical Patients (Lowest eGFR)\n")

for patient in sorted_patients[:5]:
    print(patient)

print("\nTop 5 Healthiest Patients (Highest eGFR)\n")

for patient in sorted_patients[-5:]:
    print(patient)

"""12. CKD vs Non-CKD Comparison

Calculate the following averages separately for CKD and Non-CKD patients:

•	Blood Pressure

•	Blood Sugar

•	Serum Creatinine

•	Hemoglobin

•	eGFR

"""

ckd_count = 0
non_ckd_count = 0

ckd_bp = 0
ckd_bs = 0
ckd_sc = 0
ckd_hb = 0
ckd_egfr = 0

non_bp = 0
non_bs = 0
non_sc = 0
non_hb = 0
non_egfr = 0

for patient in patients:

    if patient[7] == 1:

        ckd_count += 1

        ckd_bp += patient[1]
        ckd_bs += patient[2]
        ckd_sc += patient[3]
        ckd_hb += patient[4]
        ckd_egfr += patient[5]

    else:

        non_ckd_count += 1

        non_bp += patient[1]
        non_bs += patient[2]
        non_sc += patient[3]
        non_hb += patient[4]
        non_egfr += patient[5]

print("\nAverage Values for CKD Patients")
print("Average Blood Pressure :", round(ckd_bp / ckd_count, 2))
print("Average Blood Sugar :", round(ckd_bs / ckd_count, 2))
print("Average Serum Creatinine :", round(ckd_sc / ckd_count, 2))
print("Average Hemoglobin :", round(ckd_hb / ckd_count, 2))
print("Average eGFR :", round(ckd_egfr / ckd_count, 2))

print("\nAverage Values for Non-CKD Patients")
print("Average Blood Pressure :", round(non_bp / non_ckd_count, 2))
print("Average Blood Sugar :", round(non_bs / non_ckd_count, 2))
print("Average Serum Creatinine :", round(non_sc / non_ckd_count, 2))
print("Average Hemoglobin :", round(non_hb / non_ckd_count, 2))
print("Average eGFR :", round(non_egfr / non_ckd_count, 2))

"""13. Dataset Filtering

Create two new datasets:

•	Patients aged 50 years or above.

•	Patients whose eGFR is greater than or equal to 90.

Display the total number of records in each new dataset.


"""

age50 = []

healthy = []

for patient in patients:

    if patient[0] >= 50:
        age50.append(patient)

    if patient[5] >= 90:
        healthy.append(patient)

print("Patients Age >=50 :", len(age50))

print("Patients with eGFR >=90 :", len(healthy))

"""14. Data Validation

Check the entire dataset and identify invalid records based on the following rules:

•	No value should be negative.

•	Albumin must be between 0 and 5.

•	CKD must contain only 0 or 1.

Display all invalid records. If none exist, print an appropriate message.

"""

invalid = []

for patient in patients:

    valid = True

    for value in patient:

        if value < 0:
            valid = False

    if patient[6] < 0 or patient[6] > 5:
        valid = False

    if patient[7] != 0 and patient[7] != 1:
        valid = False

    if valid == False:
        invalid.append(patient)

if len(invalid) == 0:

    print("No Invalid Records Found.")

else:

    print("Invalid Records")

    for patient in invalid:
        print(patient)

"""15. Kidney Health Summary Report

Generate a final report containing:

•	Total Patients

•	CKD Patients

•	Non-CKD Patients

•	Average Age

•	Average Blood Pressure

•	Average Blood Sugar

•	Average Serum Creatinine

•	Average Hemoglobin

•	Average eGFR

•	Percentage of CKD Patients

•	Number of High-Risk Patients

•	Number of Patients with eGFR < 60

•	Patient(s) with the Highest Risk Score

"""

total_bp = 0
total_bs = 0
total_sc = 0
total_hb = 0
total_egfr = 0
total_age = 0

ckd = 0

egfr60 = 0

highest_score = 0

high_risk = 0

for patient in patients:

    total_age += patient[0]
    total_bp += patient[1]
    total_bs += patient[2]
    total_sc += patient[3]
    total_hb += patient[4]
    total_egfr += patient[5]

    if patient[7] == 1:
        ckd += 1

    if patient[5] < 60:
        egfr60 += 1

    if patient[1] > 150 and patient[2] > 180 and patient[3] > 2.5 and patient[5] < 45:
        high_risk += 1

    score = 0

    if patient[1] > 140:
        score += 1

    if patient[2] > 180:
        score += 1

    if patient[3] > 2.0:
        score += 1

    if patient[5] < 60:
        score += 1

    if patient[6] >= 3:
        score += 1

    if score > highest_score:
        highest_score = score

print("\nKidney Health Summary Report\n")

print("Total Patients :", len(patients))

print("CKD Patients :", ckd)

print("Non CKD Patients :", len(patients)-ckd)

print("Average Age :", round(total_age/len(patients),2))

print("Average Blood Pressure :", round(total_bp/len(patients),2))

print("Average Blood Sugar :", round(total_bs/len(patients),2))

print("Average Serum Creatinine :", round(total_sc/len(patients),2))

print("Average Hemoglobin :", round(total_hb/len(patients),2))

print("Average eGFR :", round(total_egfr/len(patients),2))

print("Percentage of CKD Patients :", round((ckd/len(patients))*100,2),"%")

print("Number of High Risk Patients :", high_risk)

print("Patients with eGFR <60 :", egfr60)

print("Highest Risk Score :", highest_score)

print("\nPatients having Highest Risk Score\n")

for patient in patients:

    score = 0

    if patient[1] > 140:
        score += 1

    if patient[2] > 180:
        score += 1

    if patient[3] > 2.0:
        score += 1

    if patient[5] < 60:
        score += 1

    if patient[6] >= 3:
        score += 1

    if score == highest_score:
        print(patient)